name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - numpy=1.21.2
  - pandas=1.3.3
  - scikit-learn=1.0
  - scipy=1.7.1
  - pip>=20
  - ipykernel
  - docopt=0.6.2
  - altair_saver
  - pip:
    - altair-data-server==0.4.1
    - jupyter-book