name: online-shoppers-env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - numpy=1.21.2
  - pandas=1.3.3
  - scikit-learn=1.0
  - scipy=1.7.1
  - pip>=20
  - ipykernel=6.5.0
  - docopt=0.6.2
  - xgboost=1.5.0
  - matplotlib=3.5.0 
  - altair_saver
  - pip:
    - altair-data-server==0.4.1
    - jupyter-book==0.12.1